In [1]:
import duckdb

con = duckdb.connect()

In [30]:
books_path = ("C:/Users/Quang/Documents/USTH/FundDS/goodreads_books.json.gz")
authors_path = ("C:/Users/Quang/Documents/USTH/FundDS/goodreads_book_authors.json.gz")
works_path = ("C:/Users/Quang/Documents/USTH/FundDS/goodreads_book_works.json.gz")
genres_path = ("C:/Users/Quang/Documents/USTH/FundDS/goodreads_book_genres_initial.json.gz")
interactions_path = ("C:/Users/Quang/Documents/USTH/FundDS/goodreads_interactions.csv")

In [47]:
con.sql("""
    DESCRIBE
    SELECT * 
    FROM read_json_auto($1)
    """,
    params=[books_path],
).show()

┌──────────────────────┬─────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│     column_name      │               column_type               │  null   │   key   │ default │  extra  │
│       varchar        │                 varchar                 │ varchar │ varchar │ varchar │ varchar │
├──────────────────────┼─────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ isbn                 │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ text_reviews_count   │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ series               │ VARCHAR[]                               │ YES     │ NULL    │ NULL    │ NULL    │
│ country_code         │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ language_code        │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ popular_shelves      │ STRUCT(count VARCHAR, "name" VARCHAR)[] │ YES     │ NULL    │ NULL    │ NULL    │
│ asin                 │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ is_ebook             │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ average_rating       │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ kindle_asin          │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│      ·               │    ·                                    │  ·      │  ·      │  ·      │  ·      │
│      ·               │    ·                                    │  ·      │  ·      │  ·      │  ·      │
│      ·               │    ·                                    │  ·      │  ·      │  ·      │  ·      │
│ publication_month    │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ edition_information  │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ publication_year     │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ url                  │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ image_url            │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ book_id              │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ ratings_count        │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ work_id              │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ title                │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ title_without_series │ VARCHAR                                 │ YES     │ NULL    │ NULL    │ NULL    │
└──────────────────────┴─────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘
  29 rows (20 shown)                                                                           6 columns

In [49]:
con.sql("""
    DESCRIBE
    SELECT * 
    FROM read_json_auto($1)
    """,
    params=[works_path],
).show()

┌───────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│            column_name            │ column_type │  null   │   key   │ default │  extra  │
│              varchar              │   varchar   │ varchar │ varchar │ varchar │ varchar │
├───────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ books_count                       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ reviews_count                     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ original_publication_month        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ default_description_language_code │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ text_reviews_count                │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ best_book_id                      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ original_publication_year         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ original_title                    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ rating_dist                       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ default_chaptering_book_id        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ original_publication_day          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ original_language_id              │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ ratings_count                     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ media_type                        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ ratings_sum                       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ work_id                           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└───────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  16 rows                                                                       6 columns

In [50]:
con.sql("""
    DESCRIBE
    SELECT * 
    FROM read_json_auto($1)
    """,
    params=[authors_path],
).show()

┌────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│    column_name     │ column_type │  null   │   key   │ default │  extra  │
│      varchar       │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ average_rating     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ author_id          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ text_reviews_count │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ name               │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ ratings_count      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [51]:
con.sql("""
    DESCRIBE
    SELECT * 
    FROM read_json_auto($1)
    """,
    params=[genres_path],
).show()

┌─────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │                                                                                                                               column_type                                                                                                                                │  null   │   key   │ default │  extra  │
│   varchar   │                                                                                                                                 varchar                                                                                                                                  │ varchar │ varchar │ varchar │ varchar │
├─────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ book_id     │ VARCHAR                                                                                                                                                                                                                                                                  │ YES     │ NULL    │ NULL    │ NULL    │
│ genres      │ STRUCT("history, historical fiction, biography" HUGEINT, fiction HUGEINT, "fantasy, paranormal" HUGEINT, "mystery, thriller, crime" HUGEINT, poetry HUGEINT, romance HUGEINT, "non-fiction" HUGEINT, children HUGEINT, "young-adult" HUGEINT, "comics, graphic" HUGEINT) │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘

In [52]:
con.sql("""
    DESCRIBE
    SELECT * 
    FROM read_csv_auto($1)
    """,
    params=[interactions_path],
).show()

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ user_id     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ book_id     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ is_read     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ rating      │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ is_reviewed │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [37]:
con.sql("""
    SELECT *
    FROM read_json_auto($1)
    LIMIT 5
    """,
    params=[books_path],
).show()

┌────────────┬────────────────────┬───────────┬──────────────┬───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬──────────┬────────────────┬─────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┬───────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────┬───────────┬─────────────────┬───────────────┬───────────────────┬─────────────────────┬──────────────────┬───────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────┬─────────┬───────────────┬─────────┬──────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────┐
│    isbn    │ text_reviews_count │  series   │ country_code │ language_code │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  popular_shelves                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │    asin    │ is_ebook │ average_rating │ kindle_asin │                                                                       similar_books                                                                        │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │  format   │                               link                                │                   authors                   │       publisher        │ num_pages │ publication_day │    isbn13     │ publication_month │ edition_information │ publication_year │                                url                                │                                        image_url                                         │ book_id │ ratings_count │ work_id │                                title                                 │                         title_without_series                         │
│  varchar   │      varchar       │ varchar[] │   varchar    │    varchar    │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      struct(count varchar, "name" varchar)[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │  varchar   │ varchar  │    varchar     │   varchar   │                                                                         varchar[]                                                                          │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        varchar                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         │  varchar  │                              varchar                              │ struct(author_id varchar, "role" varchar)[] │        varchar         │  varchar  │     varchar     │    varchar    │      varchar      │       varchar       │     varchar      │                              varchar                              │                                         varchar                                          │ varchar │    varchar    │ varchar │                               varchar                                │                               varchar                                │

In [38]:
con.sql("""
    SELECT *
    FROM read_json_auto($1)
    LIMIT 5
    """,
    params=[authors_path],
).df()

  average_rating author_id text_reviews_count              name ratings_count
0           3.98    604031                  7  Ronald J. Fields            49
1           4.08    626222              28716     Anita Diamant        546796
2           3.92     10333               5075    Barbara Hambly        122118
3           3.68      9212              36262   Jennifer Weiner        888522
4           3.82    149918                 96     Nigel Pennick          1740

In [40]:
con.sql("""
    SELECT *
    FROM read_json_auto($1)
    LIMIT 5
    """,
    params=[works_path],
).df()

,books_count,reviews_count,original_publication_month,default_description_language_code,text_reviews_count,best_book_id,original_publication_year,original_title,rating_dist,default_chaptering_book_id,original_publication_day,original_language_id,ratings_count,media_type,ratings_sum,work_id
0,1,6,8,,1,5333265,1984,W. C. Fields: A Life on Film,5:1|4:1|3:1|2:0|1:0|total:3,,,,3,book,12,5400751
1,22,10162,,,741,25717,2001,Good Harbor,5:517|4:1787|3:2763|2:966|1:196|total:6229,,,,6229,book,20150,1323437
2,2,268,,,7,7327624,1987,,5:49|4:58|3:26|2:5|1:3|total:141,,,,141,book,568,8948723
3,38,89252,7,,3504,6066819,2009,Best Friends Forever,5:9152|4:16855|3:19507|2:6210|1:1549|total:53273,,14,,53273,book,185670,6243154
4,2,49,,,5,287140,1990,Runic Astrology: Starcraft and Timekeeping in ...,5:6|4:1|3:3|2:3|1:2|total:15,,,,15,book,51,278577

In [41]:
con.sql("""
    SELECT *
    FROM read_json_auto($1)
    LIMIT 5
    """,
    params=[genres_path],
).show()

┌─────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ book_id │                                                                                                                                  genres                                                                                                                                  │
│ varchar │ struct("history, historical fiction, biography" hugeint, fiction hugeint, "fantasy, paranormal" hugeint, "mystery, thriller, crime" hugeint, poetry hugeint, romance hugeint, "non-fiction" hugeint, children hugeint, "young-adult" hugeint, "comics, graphic" hugeint) │
├─────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 5333265 │ {'history, historical fiction, biography': 1, 'fiction': NULL, 'fantasy, paranormal': NULL, 'mystery, thriller, crime': NULL, 'poetry': NULL, 'romance': NULL, 'non-fiction': NULL, 'children': NULL, 'young-adult': NULL, 'comics, graphic': NULL}                      │
│ 1333909 │ {'history, historical fiction, biography': 5, 'fiction': 219, 'fantasy, paranormal': NULL, 'mystery, thriller, crime': NULL, 'poetry': NULL, 'romance': NULL, 'non-fiction': NULL, 'children': NULL, 'young-adult': NULL, 'comics, graphic': NULL}                       │
│ 7327624 │ {'history, historical fiction, biography': NULL, 'fiction': 8, 'fantasy, paranormal': 31, 'mystery, thriller, crime': 1, 'poetry': 1, 'romance': NULL, 'non-fiction': NULL, 'children': NULL, 'young-adult': NULL, 'comics, graphic': NULL}                              │
│ 6066819 │ {'history, historical fiction, biography': NULL, 'fiction': 555, 'fantasy, paranormal': NULL, 'mystery, thriller, crime': 10, 'poetry': NULL, 'romance': 23, 'non-fiction': NULL, 'children': NULL, 'young-adult': NULL, 'comics, graphic': NULL}                        │
│ 287140  │ {'history, historical fiction, biography': NULL, 'fiction': NULL, 'fantasy, paranormal': NULL, 'mystery, thriller, crime': NULL, 'poetry': NULL, 'romance': NULL, 'non-fiction': 3, 'children': NULL, 'young-adult': NULL, 'comics, graphic': NULL}                      │
└─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [43]:
con.sql("""
    SELECT *
    FROM read_csv_auto($1)
    LIMIT 5
    """,
    params=[interactions_path],
).df()

   user_id  book_id  is_read  rating  is_reviewed
0        0      948        1       5            0
1        0      947        1       5            1
2        0      946        1       5            0
3        0      945        1       5            0
4        0      944        1       5            0

In [7]:
con.sql("""
    SELECT COUNT(*) AS total_books
    FROM read_json_auto($1)
    """,
    params=[books_path],
).show()

┌─────────────┐
│ total_books │
│    int64    │
├─────────────┤
│     2360655 │
└─────────────┘

In [44]:
con.sql("""
    SELECT COUNT(*) AS total_books
    FROM read_json_auto($1)
    """,
    params=[works_path],
).show()

┌─────────────┐
│ total_books │
│    int64    │
├─────────────┤
│     1521962 │
└─────────────┘

In [17]:
con.sql("""
    SELECT COUNT(*) AS total_books
    FROM read_json_auto($1)
    """,
    params=[interactions_path],
).show()

┌─────────────┐
│ total_books │
│    int64    │
├─────────────┤
│   228648342 │
└─────────────┘